# Permalinks
permalink:           pretty

# Setup
title:               Blog
tagline:
url:
paginate:            5
baseurl:             ""

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
